server:
  port: 8080

rpc:
  jon:
    provider:
      # rpc server
      serverAddress: 127.0.0.1:27880
      # zookeeper server
      registryAddress: 127.0.0.1:2181
      # registry center type, zookeeper/nacos/apoll/etcd/eureka
      registryType: zookeeper
      #registry loadbalance type: zkconsistenthash
      registryLoadBalanceType: zkconsistenthash
      # reflect type, value is jdk or cglib
      reflectType: cglib
      # heartbeatInterval
      heartbeatInterval: 30000
      # scanNotActiveChannelInterval
      scanNotActiveChannelInterval: 60000
      # enableResultCache
      enableResultCache: true
      # resultCacheExpire
      resultCacheExpire: 10000
      # corePoolSize
      corePoolSize: 16
      # maximumPoolSize
      maximumPoolSize: 16
      # flowType
      flowType: print



